# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quick_lm <- function(y, X) {
    .Call('ri2_quick_lm', PACKAGE = 'ri2', y, X)
}

